services:
  - type: web
    name: studybuddy-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Main.py --server.port=$PORT
    envVars:
      - key: API_URL
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true